services:
  - type: web
    name: sauna-fastapi
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn direct_html_app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        sync: false

  - type: web
    name: sauna-streamlit
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app/app.py --server.port 10000"
    envVars:
      - key: DATABASE_URL
        sync: false

envVars:
  - key: DATABASE_URL
    sync: false