name: Scheduled Sauna Scraping

on:
  schedule:
    - cron: "*/15 * * * *"  # 毎15分
  workflow_dispatch:
    
jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render service and run scraping
        run: |
          # 1. まずサービスを起こす
          echo "Waking up the service..."
          curl -s https://saunaranking-ver2-fastapi.onrender.com/health
          
          # 2. サービスの起動を待つ（30秒）
          echo "Waiting for service to wake up..."
          sleep 30
          
          # 3. スクレイピングを実行
          echo "Starting scraping..."
          response=$(curl -s -w "\n%{http_code}" https://saunaranking-ver2-fastapi.onrender.com/api/github-action-scraping)
          
          # レスポンスからステータスコードと本文を分離
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          # 結果を出力
          echo "Status code: $status_code"
          echo "Response body: $body"
          
          # エラーチェック
          if [ "$status_code" -ne 200 ]; then
            echo "Error: Scraping failed"
            exit 1
          fi

      - name: Wake up Streamlit app
        run: |
          echo "Waking up Streamlit..."
          curl -s https://sauna-ranking-ver2.onrender.com
